### ISSUE TITLE
Javascript Track Courses to be Completed

### ISSUE THREAD

**Issue by crobinson0405** [crobinson0405/Treehouse#2]
## TODO

_Courses left to complete the Treehouse Javascript Track_
- [ ] JavaScript Loops, Arrays & Objects
- [ ] jQuery Basics
- [ ] “Using jQuery Plugins” + “Interactive Webpages with JavaScript” courses
- [ ] AJAX Basics
- [ ] “Understanding “this” in JavaScript (shortworkshop)” + Object-Oriented JavaScript” + “The Module Pattern in JavaScript (short workshop)”
- [ ] “Node.js Basics” + “Build a Simple Dynamic Site with Node.js”
- [ ] “npm Basics” + “Using npm as a Task Runner (short workshop)” + “Git Basics”
- [ ] “Express Basics” + “Gulp Basics”
- [ ]  “Angular Basics” + “Mongo Basics” + “Build a MEAN Application”
- [ ]  “JavaScript Unit Testing”

:grin: :100: :us: 

cc @...
